"""Add difficulty field

Revision ID: d1ff00000000
Revises: 48d8250d19bd
Create Date: 2026-03-27 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ff00000000'
down_revision = '48d8250d19bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('difficulty', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'difficulty')
    # ### end Alembic commands ###
